@startuml 游戏流程
title 游戏流程图
===游戏初始化==
玩家 -> 游戏 : 启动
游戏 -> 游戏内核 : 初始化
游戏内核 -> 玩家管理器 : 记录玩家
游戏内核 -> 地图管理器 : 随机生成小地图
地图管理器 -> 小地图 : 配置资源
游戏内核 -> 任务管理器 : 随机生成任务
任务管理器 -> 地图管理器 : 在小地图中放置任务NPC
游戏内核 -> 敌人管理器 : 根据玩家人数等，设定参数
游戏内核 -> 结局系统 : 开始游戏进度监听
游戏内核 -> 游戏 : 初始化完成
游戏 -> 玩家 : 游戏开始
===游戏逻辑==
玩家 -> 游戏 : 操作
游戏 -> 游戏内核 : 传递操作
游戏内核 -> 游戏内核 : 1.打开界面\n包裹、任务etc
游戏内核 -> 任务管理器 : 1.1.任务解锁、任务信息查看
游戏内核 -> 玩家管理器 : 2.传递玩家操作
玩家管理器 -> 小地图 : 2.1获取资源
玩家管理器 -> 玩家管理器 : 2.2传递/消耗资源
玩家管理器 -> 敌人管理器 : 2.3杀死敌人
玩家管理器 -> 任务NPC : 2.4交互
任务NPC -> 任务管理器 : 2.4任务进度更新
===游戏结局==
结局系统 -> 结局系统 : 满足游戏结束条件
结局系统 -> 游戏内核 : 游戏结束
结局系统 -> 结局系统 : 根据监听结果计算结局
结局系统 -> 游戏内核 : 告知结局
游戏内核 -> 游戏 : 显示结局
===游戏结束==
@enduml
